Repository ibm-openbmc/webui-vue, pull requests merged in 2024-12, with the labels that each got.

#305 Updated IBM i service functions
  src/locales/en-US.json
  src/views/Logs/IBMiServiceFunctions/IBMiServiceFunctions.vue
Labels: 1110, 1060

#315 Fixed Policies page toggle functionality
  src/store/modules/SecurityAndAccess/PoliciesStore.js
Labels: 1050, 1110, 1060

#319 Info alert for non idle power saver modes
  src/locales/en-US.json
  src/views/ResourceManagement/Power/PowerIdleSaver.vue
Labels: 1110

#320 Implemented Certificates page
  src/assets/styles/bmc/custom/_forms.scss
  src/components/Global/FormFile.vue
  src/router/routes.js
  src/store/index.js
  src/store/modules/GlobalStore.js
  src/store/modules/SecurityAndAccess/CertificatesStore.js
  src/store/modules/SecurityAndAccess/UserManagementStore.js
  src/views/SecurityAndAccess/Certificates/Certificates.vue
  src/views/SecurityAndAccess/Certificates/CsrCountryCodes.js
  src/views/SecurityAndAccess/Certificates/ModalGenerateCsr.vue
  src/views/SecurityAndAccess/Certificates/ModalUploadCertificate.vue
Labels: vue3, 1060-vue3, 1110-vue3

#311 Implemented System Parameters page - 1110
  src/router/routes.js
  src/store/index.js
  src/store/modules/ResourceManagement/SystemParametersStore.js
  src/views/ResourceManagement/SystemParameters/AggressivePrefetch.vue
  src/views/ResourceManagement/SystemParameters/FrequencyCap.vue
  src/views/ResourceManagement/SystemParameters/LateralCastOut.vue
  src/views/ResourceManagement/SystemParameters/RuntimeProcessorDiagnostic.vue
  src/views/ResourceManagement/SystemParameters/SystemParameters.vue
Labels: vue3, 1110-vue3

#310 Implemented System Parameters Page
  src/router/routes.js
  src/store/index.js
  src/store/modules/ResourceManagement/SystemParametersStore.js
  src/views/ResourceManagement/SystemParameters/AggressivePrefetch.vue
  src/views/ResourceManagement/SystemParameters/FrequencyCap.vue
  src/views/ResourceManagement/SystemParameters/LateralCastOut.vue
  src/views/ResourceManagement/SystemParameters/RuntimeProcessorDiagnostic.vue
  src/views/ResourceManagement/SystemParameters/SystemParameters.vue
Labels: vue3, 1060-vue3

#313 1MD: Spare core: Added toast messages for Event logs
  src/locales/en-US.json
  src/store/modules/Logs/EventLogStore.js
  src/views/Logs/EventLogs/EventLogs.vue
Labels: 1110

#318 Implemented Clear secret key and given privileges to service
  src/locales/en-US.json
  src/store/modules/SecurityAndAccess/UserManagementStore.js
  src/views/SecurityAndAccess/UserManagement/ModalUser.vue
  src/views/SecurityAndAccess/UserManagement/UserManagement.vue
Labels: 1110

#312 Implemented PCIe Topology page
  src/assets/styles/bmc/custom/_card.scss
  src/assets/styles/bmc/custom/_tables.scss
  src/router/routes.js
  src/store/index.js
  src/store/modules/Authentication/AuthenticationStore.js
  src/store/modules/GlobalStore.js
  src/store/modules/HardwareStatus/PcieTopologyStore.js
  src/views/HardwareStatus/Inventory/Inventory.vue
  src/views/HardwareStatus/Inventory/InventoryServiceIndicator.vue
  src/views/HardwareStatus/Inventory/InventoryTableChassis.vue
  src/views/HardwareStatus/PcieTopology/IdentifyLedsModal.vue
  src/views/HardwareStatus/PcieTopology/PcieTopology.vue
  src/views/HardwareStatus/PcieTopology/ResetLinkModal.vue
  src/views/HardwareStatus/Sensors/Sensors.vue
  src/views/Login/Login.vue
  src/views/Logs/AuditLogs/AuditLogs.vue
Labels: vue3, 1060-vue3, 1110-vue3

#322 Regenerate package-lock file for x86 systems
  package-lock.json
Labels: vue3, 1060-vue3

#323 1110-vue3: Regenerate package-lock file for x86 systems
  package-lock.json
Labels: vue3, 1110-vue3

#321 Fixed IBMi Parameters reverting to default on first saving
  src/views/Operations/ServerPowerOperations/BiosSettings.vue
  src/views/Operations/ServerPowerOperations/BootSettings.vue
Labels: 1110, 1060

#325 Fixed Token issue
  src/store/api.js
  src/store/modules/Authentication/AuthenticanStore.js
Labels: 1110

#326 Fixed Resolve error message
  src/store/modules/Logs/EventLogStore.js
  src/views/Logs/EventLogs/EventLogs.vue
Labels: 1110

#327 Implemented LLDP Toggle
  src/locales/en-US.json
  src/store/modules/Settings/NetworkStore.js
  src/views/Settings/Network/Network.vue
  src/views/Settings/Network/NetworkInterfaceSettings.vue
Labels: 1110
