Repository ibm-openbmc/webui-vue, pull requests merged in 2024-06, with the labels that each got.

#243 Added "User unauthorized" in 1020
  src/locales/en-US.json
Labels: priority_1, 1020

#249 Vue3: Fix Bootstrap 5 changes and styling issues
  src/assets/styles/bmc/custom/_alert.scss
  src/assets/styles/bmc/custom/_badge.scss
  src/assets/styles/bmc/custom/_base.scss
  src/assets/styles/bmc/custom/_buttons.scss
  src/assets/styles/bmc/custom/_calendar.scss
  src/assets/styles/bmc/custom/_card.scss
  src/assets/styles/bmc/custom/_dropdown.scss
  src/assets/styles/bmc/custom/_forms.scss
  src/assets/styles/bmc/custom/_modal.scss
  src/assets/styles/bmc/custom/_pagination.scss
  src/assets/styles/bmc/custom/_section-divider.scss
  src/assets/styles/bmc/custom/_tables.scss
  src/assets/styles/bmc/custom/_toasts.scss
  src/assets/styles/bmc/helpers/_functions.scss
  src/components/AppHeader/AppHeader.vue
  src/components/AppNavigation/AppNavigation.vue
  src/components/Global/LoadingBar.vue
  src/components/Global/TableToolbar.vue
  src/layouts/LoginLayout.vue
  src/main.js
Labels: vue3

#238 Save button position
  src/views/Operations/ServerPowerOperations/BiosSettings.vue
  src/views/Operations/ServerPowerOperations/BootSettings.vue
Labels: 1110

#250 Fixed Arrow icon
  src/views/Operations/ServerPowerOperations/BiosSettings.vue
  src/views/ResourceManagement/Power/PowerPerformanceModes.vue
Labels: 1050, 1110, 1060, 1030
