Repository ibm-openbmc/webui-vue, pull requests merged in 2024-10, with the labels that each got.

#290 Update Predictive dynamic memory dealloc help text
  src/locales/en-US.json
  src/store/modules/ResourceManagement/ResourceMemoryStore.js
  src/views/ResourceManagement/Memory/Memory.vue
Labels: vue3, 1060-vue3, 1110-vue3

#293 Removed grey out option in Policies page
  src/views/SecurityAndAccess/Policies/Policies.vue
Labels: vue3, 1060-vue3, 1110-vue3

#294 Updated Policies page
  src/store/api.js
  src/store/modules/SecurityAndAccess/PoliciesStore.js
Labels: vue3, 1060-vue3, 1110-vue3

#292 Removed grey out option in Policies page
  src/views/SecurityAndAccess/Policies/Policies.vue
Labels: 1050, 1110, 1060, 1030

#284 Implemented Sessions page
  src/components/Global/TableToolbar.vue
  src/router/routes.js
  src/store/index.js
  src/store/modules/SecurityAndAccess/SessionsStore.js
  src/views/SecurityAndAccess/Sessions/Sessions.vue
Labels: vue3, 1060-vue3, 1110-vue3

#296 Fixed “View all” issue in pagination
  src/components/Composables/usePaginationComposable.js
  src/views/HardwareStatus/Sensors/Sensors.vue
  src/views/Logs/AuditLogs/AuditLogs.vue
  src/views/SecurityAndAccess/Sessions/Sessions.vue
Labels: vue3, 1060-vue3, 1110-vue3

#297 Implement Firmware page
  .eslintrc.cjs
  src/assets/styles/bmc/custom/_card.scss
  src/assets/styles/bmc/custom/_forms.scss
  src/components/Global/FormFile.vue
  src/components/Global/Toast.vue
  src/layouts/AppLayout.vue
  src/router/routes.js
  src/store/index.js
  src/store/modules/GlobalStore.js
  src/store/modules/HardwareStatus/BmcStore.js
  src/store/modules/Operations/FirmwareStore.js
  src/store/modules/ResourceManagement/LicenseStore.js
  src/views/Operations/Firmware/Firmware.vue
  src/views/Operations/Firmware/FirmwareAccessKey.vue
  src/views/Operations/Firmware/FirmwareAlertServerPower.vue
  src/views/Operations/Firmware/FirmwareCardsBmc.vue
  src/views/Operations/Firmware/FirmwareCardsHost.vue
  src/views/Operations/Firmware/FirmwareFormUpdate.vue
  src/views/Operations/Firmware/FirmwareModalSwitchToRunning.vue
  src/views/Operations/Firmware/FirmwareModalUpdateFirmware.vue
Labels: vue3, 1060-vue3

#298 Implement Firmware page:1110-vue3
  .env.ibm
  .eslintrc.cjs
  src/assets/styles/bmc/custom/_card.scss
  src/assets/styles/bmc/custom/_forms.scss
  src/components/Global/FormFile.vue
  src/components/Global/Toast.vue
  src/layouts/AppLayout.vue
  src/locales/en-US.json
  src/router/routes.js
  src/store/index.js
  src/store/modules/GlobalStore.js
  src/store/modules/HardwareStatus/BmcStore.js
  src/store/modules/Operations/FirmwareStore.js
  src/store/modules/ResourceManagement/LicenseStore.js
  src/views/Operations/Firmware/Firmware.vue
  src/views/Operations/Firmware/FirmwareAccessKey.vue
  src/views/Operations/Firmware/FirmwareAlertServerPower.vue
  src/views/Operations/Firmware/FirmwareCardsBmc.vue
  src/views/Operations/Firmware/FirmwareCardsHost.vue
  src/views/Operations/Firmware/FirmwareFormUpdate.vue
  src/views/Operations/Firmware/FirmwareModalSwitchToRunning.vue
  src/views/Operations/Firmware/FirmwareModalUpdateFirmware.vue
Labels: vue3, 1110-vue3

#273 Removed compression Plugin
  vue.config.js
Labels: 1110, 1060

#291 Implemented Inventory page
  src/assets/styles/bmc/custom/_card.scss
  src/assets/styles/bmc/custom/_tables.scss
  src/components/Composables/useJumpLinkComposable.js
  src/components/Composables/useSearchFilterComposable.js
  src/components/Composables/useTableRowExpandComposable.js
  src/components/Global/InfoTooltip.vue
  src/components/Global/Search.vue
  src/router/routes.js
  src/store/index.js
  src/store/modules/HardwareStatus/AssemblyStore.js
  src/store/modules/HardwareStatus/ChassisStore.js
  src/store/modules/HardwareStatus/FabricAdaptersStore.js
  src/store/modules/HardwareStatus/FanStore.js
  src/store/modules/HardwareStatus/MemoryStore.js
  src/store/modules/HardwareStatus/PcieSlotsStore.js
  src/store/modules/HardwareStatus/PowerSupplyStore.js
  src/store/modules/HardwareStatus/ProcessorStore.js
  src/store/modules/HardwareStatus/SystemStore.js
  src/store/modules/Logs/AuditLogsStore.js
  src/views/HardwareStatus/Inventory/Inventory.vue
  src/views/HardwareStatus/Inventory/InventoryFabricAdapters.vue
  src/views/HardwareStatus/Inventory/InventoryServiceIndicator.vue
  src/views/HardwareStatus/Inventory/InventoryTableAssembly.vue
  src/views/HardwareStatus/Inventory/InventoryTableBmcManager.vue
  src/views/HardwareStatus/Inventory/InventoryTableChassis.vue
  src/views/HardwareStatus/Inventory/InventoryTableDimmSlot.vue
  src/views/HardwareStatus/Inventory/InventoryTableFans.vue
  src/views/HardwareStatus/Inventory/InventoryTablePcieSlots.vue
  src/views/HardwareStatus/Inventory/InventoryTablePowerSupplies.vue
  src/views/HardwareStatus/Inventory/InventoryTableProcessors.vue
  src/views/HardwareStatus/Inventory/InventoryTableSystem.vue
  src/views/HardwareStatus/Sensors/Sensors.vue
  src/views/Logs/AuditLogs/AuditLogs.vue
Labels: vue3, 1060-vue3, 1110-vue3

#300 Fix for date picker range error
  src/components/Global/TableDateFilter.vue
Labels: vue3, 1060-vue3, 1110-vue3

#299 Updated Immediate Test Request
  src/views/ResourceManagement/SystemParameters/RuntimeProcessorDiagnostic.vue
Labels: 1110

#268 Removed info message display for readonly users
  src/store/modules/Operations/ControlStore.js
  src/views/Operations/ServerPowerOperations/ServerPowerOperations.vue
Labels: 1050, 1110, 1060, 1030
