Repository ibm-openbmc/webui-vue, pull requests merged in 2024-05, with the labels that each got.

#229 1050: Fixed Local port location
  src/store/modules/HardwareStatus/PcieTopologyStore.js
Labels: 1050

#240 Fixed LDAP login issue
  src/store/modules/GlobalStore.js
Labels: 1050, 1110, 1060, 1030, priority_1

#235 Fixed Navigation bar loading issue
  src/components/AppNavigation/AppNavigation.vue
  src/components/Mixins/LoadingBarMixin.js
  src/views/HardwareStatus/PcieTopology/PcieTopology.vue
  src/views/Notices/Notices.vue
  src/views/Operations/FactoryReset/FactoryReset.vue
  src/views/Operations/HostConsole/HostConsole.vue
  src/views/Operations/KeyClear/KeyClear.vue
  src/views/Operations/ServiceLoginConsoles/ServiceLoginConsoles.vue
Labels: 1110, 1060

#242 Navigation bar display issue
  src/components/AppNavigation/AppNavigation.vue
  src/components/Mixins/LoadingBarMixin.js
  src/views/HardwareStatus/PcieTopology/PcieTopology.vue
  src/views/Notices/Notices.vue
  src/views/Operations/FactoryReset/FactoryReset.vue
  src/views/Operations/HostConsole/HostConsole.vue
  src/views/Operations/KeyClear/KeyClear.vue
  src/views/Operations/ServiceLoginConsoles/ServiceLoginConsoles.vue
Labels: 1030

#239 Navigation bar loading issue
  src/components/AppNavigation/AppNavigation.vue
  src/components/Mixins/LoadingBarMixin.js
  src/views/HardwareStatus/PcieTopology/PcieTopology.vue
  src/views/Notices/Notices.vue
  src/views/Operations/FactoryReset/FactoryReset.vue
  src/views/Operations/HostConsole/HostConsole.vue
  src/views/Operations/KeyClear/KeyClear.vue
  src/views/Operations/ServiceLoginConsoles/ServiceLoginConsoles.vue
Labels: 1050

#241 Displaying empty for progress code '00000000'
  src/views/Logs/PostCodeLogs/PostCodes.vue
Labels: 1050, 1110, 1060, 1030, priority_1
