Repository ibm-openbmc/webui-vue, pull requests merged in 2024-09, with the labels that each got.

#278 Implemented Memory page
  src/assets/styles/bmc/custom/_forms.scss
  src/components/Composables/useJumpLinkComposable.js
  src/locales/en-US.json
  src/router/routes.js
  src/store/index.js
  src/store/modules/GlobalStore.js
  src/store/modules/ResourceManagement/ResourceMemoryStore.js
  src/views/ResourceManagement/Memory/Memory.vue
Labels: vue3

#276 Fixed alert message info when dump is being generated
  src/store/modules/Logs/DumpsStore.js
Labels: 1050, 1110, 1060, 1030

#279 Implemented IBM i service functions
  src/router/routes.js
  src/store/index.js
  src/store/modules/GlobalStore.js
  src/store/modules/Logs/IBMiServiceFunctionsStore.js
  src/views/Logs/IBMiServiceFunctions/IBMiServiceFunctions.vue
Labels: vue3

#277 Implemented Audit logs
  src/components/Composables/useTableFilterComposable.js
  src/components/Composables/useTableRowExpandComposable.js
  src/components/Global/TableDateFilter.vue
  src/router/routes.js
  src/store/api.js
  src/store/index.js
  src/store/modules/Logs/AuditLogsStore.js
  src/views/Logs/AuditLogs/AuditLogs.vue
Labels: vue3

#283 Optimized status icon in Sensors page
  src/components/Composables/useDataFormatterGlobal.js
  src/views/HardwareStatus/Sensors/Sensors.vue
Labels: vue3

#287 Updated Predictive dynamic memory dealloc help text
  src/locales/en-US.json
  src/store/modules/ResourceManagement/ResourceMemoryStore.js
  src/views/ResourceManagement/Memory/Memory.vue
Labels: 1110, 1060

#288 Updated Redfish URI for Executing Panel functions
  src/store/modules/Logs/IBMiServiceFunctionsStore.js
Labels: 1110

#282 Implemented Concurrent Maintenance Page
  src/router/routes.js
  src/store/index.js
  src/store/modules/HardwareStatus/ConcurrentMaintenanceStore.js
  src/views/HardwareStatus/ConcurrentMaintenance/ConcurrentMaintenance.vue
Labels: vue3

#286 Power page modal fix
  src/views/ResourceManagement/Power/ModalPowerPerformanceModes.vue
Labels: vue3

#289 Fix service login certificate expiry checks
  src/views/SecurityAndAccess/Certificates/Certificates.vue
Labels: 1110

#285 Updated Power Restore Policy
  src/store/modules/Settings/PowerPolicyStore.js
Labels: 1110
