Repository ibm-openbmc/webui-vue, pull requests merged in 2024-08, with the labels that each got.

#261 Removed TFTP support in the GUI
  .env.ibm
  src/locales/en-US.json
  src/store/modules/Operations/FirmwareStore.js
  src/views/Operations/Firmware/FirmwareFormUpdate.vue
Labels: 1110

#264 Displaying MinMif on GUI
  src/store/modules/Operations/FirmwareStore.js
  src/views/Operations/Firmware/Firmware.vue
Labels: 1110, 1060

#262 Implemented Policies page
  src/assets/styles/bmc/custom/_forms.scss
  src/components/Global/InfoTooltip.vue
  src/components/Global/StatusIcon.vue
  src/router/routes.js
  src/store/modules/SecurityAndAccess/PoliciesStore.js
  src/store/modules/SecurityAndAccess/UserManagementStore.js
  src/views/Login/Login.vue
  src/views/SecurityAndAccess/Policies/Policies.vue
Labels: vue3

#255 Implemented Sensors
  src/assets/styles/bmc/custom/_badge.scss
  src/assets/styles/bmc/custom/_pagination.scss
  src/assets/styles/bmc/custom/_tables.scss
  src/components/Composables/usePaginationComposable.js
  src/components/Composables/useSearchFilterComposable.js
  src/components/Composables/useTableFilterComposable.js
  src/components/Composables/useTableSelectableComposable.js
  src/components/Global/PageTitle.vue
  src/components/Global/Search.vue
  src/components/Global/TableFilter.vue
  src/components/Global/TableToolbar.vue
  src/components/Global/TableToolbarExport.vue
  src/router/routes.js
  src/store/modules/HardwareStatus/SensorsStore.js
  src/views/HardwareStatus/Sensors/Sensors.vue
Labels: vue3

#258 Implemented Predictive dynamic memory deallocation
  src/locales/en-US.json
  src/store/modules/ResourceManagement/ResourceMemoryStore.js
  src/views/ResourceManagement/Memory/Memory.vue
Labels: 1110, 1060

#260 Adding SNMP IP via GUI
  src/views/Settings/SnmpAlerts/SnmpAlerts.vue
Labels: 1110

#256 Monitoring tasks while generating resource dump
  src/locales/en-US.json
  src/store/modules/Logs/DumpsStore.js
  src/views/Logs/Dumps/DumpsForm.vue
Labels: 1050, 1110, 1060, 1030

#271 Fixed alert informational message in Server Power Operations page
  src/views/Operations/ServerPowerOperations/BootSettings.vue
Labels: 1110, 1060

#270 Fixed values updation on Capacity on Demand page
  src/views/ResourceManagement/CapacityOnDemand/CapacityOnDemandActivation.vue
Labels: 1050, 1110, 1060, 1030

#275 Implemented Power page
  src/assets/styles/bmc/custom/_bootstrap-grid.scss
  src/assets/styles/bmc/custom/_buttons.scss
  src/assets/styles/bmc/custom/_forms.scss
  src/assets/styles/bmc/custom/_tables.scss
  src/components/Composables/useLoadingBarComposable.js
  src/components/Global/PageSection.vue
  src/router/routes.js
  src/store/modules/GlobalStore.js
  src/store/modules/ResourceManagement/PowerControlStore.js
  src/views/ResourceManagement/Power/ModalPowerPerformanceModes.vue
  src/views/ResourceManagement/Power/Power.vue
  src/views/ResourceManagement/Power/PowerCap.vue
  src/views/ResourceManagement/Power/PowerIdleSaver.vue
  src/views/ResourceManagement/Power/PowerPerformanceModes.vue
  src/views/ResourceManagement/Power/TablePowerPerformanceModes.vue
Labels: vue3
