Repository ibm-openbmc/webui-vue, pull requests merged in 2025-04, with the labels that each got.

#398 DHCP NTP servers list displayed on GUI - 1060
  src/locales/en-US.json
  src/store/modules/Settings/DateTimeStore.js
  src/views/Settings/DateTime/DateTime.vue
Labels: 1050, 1060

#400 DHCP NTP servers list styling change
  src/views/Settings/DateTime/DateTime.vue
Labels: 1110

#384 Implemented Profile settings page
  src/components/Global/InfoTooltipPassword.vue
  src/router/routes.js
  src/store/modules/GlobalStore.js
  src/store/modules/Logs/AuditLogsStore.js
  src/views/ProfileSettings/ProfileSettings.vue
Labels: vue3, 1060-vue3, 1110-vue3

#401 Alert message on Memory page
  src/locales/en-US.json
  src/views/ResourceManagement/Memory/Memory.vue
Labels: 1110, 1060

#340 Updated ClearAll message in Deconfig records
  src/locales/en-US.json
  src/store/modules/Logs/DeconfigurationRecordsStore.js
  src/views/Logs/DeconfigurationRecords/DeconfigurationRecords.vue
Labels: 1110

#403 Implement Network page
  src/components/Global/TableRowAction.vue
  src/router/routes.js
  src/store/modules/Settings/NetworkStore.js
  src/views/Settings/Network/ModalDns.vue
  src/views/Settings/Network/ModalHostname.vue
  src/views/Settings/Network/ModalIpv4.vue
  src/views/Settings/Network/ModalIpv6.vue
  src/views/Settings/Network/ModalIpv6StaticDefaultGateway.vue
  src/views/Settings/Network/Network.vue
  src/views/Settings/Network/NetworkGlobalSettings.vue
  src/views/Settings/Network/NetworkInterfaceSettings.vue
  src/views/Settings/Network/TableDns.vue
  src/views/Settings/Network/TableIpv4.vue
  src/views/Settings/Network/TableIpv6.vue
  src/views/Settings/Network/TableIpv6StaticDefaultGateway.vue
Labels: vue3, 1060-vue3, 1110-vue3

#404 Implemented Login page
  src/layouts/LoginLayout.vue
  src/store/api.js
  src/store/modules/Authentication/AuthenticationStore.js
  src/views/Login/Login.vue
Labels: vue3, 1060-vue3, 1110-vue3

#405 Added data-test-ids for MFA automation
  src/views/Login/ModalOtpGenerate.vue
  src/views/SecurityAndAccess/UserManagement/RegisterOtpModal.vue
  src/views/SecurityAndAccess/UserManagement/UserManagement.vue
Labels: 1110
