Repository ibm-openbmc/webui-vue, pull requests merged in 2025-03, with the labels that each got.

#331 Implemented User Management: 1060
  src/components/Composables/useTableSelectableComposable.js
  src/components/Global/InfoTooltipPassword.vue
  src/router/routes.js
  src/store/modules/GlobalStore.js
  src/store/modules/SecurityAndAccess/UserManagementStore.js
  src/utilities/GlobalConstants.js
  src/views/SecurityAndAccess/UserManagement/ModalSettings.vue
  src/views/SecurityAndAccess/UserManagement/ModalUser.vue
  src/views/SecurityAndAccess/UserManagement/TableRoles.vue
  src/views/SecurityAndAccess/UserManagement/UserManagement.vue
Labels: vue3, 1060-vue3, 1110-vue3

#386 Fix api call string format - PCIe topology
  src/store/modules/HardwareStatus/PcieTopologyStore.js
Labels: vue3, 1060-vue3, 1110-vue3

#383 Implement Field core override
  src/assets/styles/bmc/custom/_forms.scss
  src/router/routes.js
  src/store/index.js
  src/store/modules/ResourceManagement/FieldCoreOverrideStore.js
  src/views/ResourceManagement/FieldCoreOverride/FieldCoreOverride.vue
  src/views/ResourceManagement/FieldCoreOverride/FieldCoreOverrideConfiguration.vue
  src/views/ResourceManagement/FieldCoreOverride/FieldCoreOverrideInfo.vue
Labels: vue3, 1060-vue3, 1110-vue3

#380 Updated Upstream Ports
  src/store/modules/HardwareStatus/PcieTopologyStore.js
Labels: 1110

#385 Implement service login console
  src/router/routes.js
  src/store/modules/GlobalStore.js
  src/store/modules/HardwareStatus/ChassisStore.js
  src/views/Operations/ServiceLoginConsoles/ServiceLogin.vue
  src/views/Operations/ServiceLoginConsoles/ServiceLoginConsoles.vue
Labels: vue3, 1060-vue3, 1110-vue3

#363 Fixed Clear all Deconfig records
  src/locales/en-US.json
  src/views/Logs/DeconfigurationRecords/DeconfigurationRecords.vue
Labels: 1110

#388 Fixed Search functionality
  src/components/Global/Search.vue
Labels: vue3, 1060-vue3, 1110-vue3

#387 Implemented Progress logs
  src/router/routes.js
  src/store/index.js
  src/store/modules/Logs/PostCodeLogsStore.js
  src/views/Logs/PostCodeLogs/PostCodeLogs.vue
  src/views/Logs/PostCodeLogs/PostCodes.vue
Labels: vue3, 1060-vue3, 1110-vue3

#376 Implemented Overview page
  src/store/index.js
  src/store/modules/Logs/DumpsStore.js
  src/store/modules/Settings/NetworkStore.js
  src/views/Overview/ModalAssetTag.vue
  src/views/Overview/Overview.vue
  src/views/Overview/OverviewCard.vue
  src/views/Overview/OverviewDumps.vue
  src/views/Overview/OverviewEvents.vue
  src/views/Overview/OverviewFirmware.vue
  src/views/Overview/OverviewInventory.vue
  src/views/Overview/OverviewNetwork.vue
  src/views/Overview/OverviewPower.vue
  src/views/Overview/OverviewQuickLinks.vue
  src/views/Overview/OverviewServer.vue
Labels: vue3, 1060-vue3, 1110-vue3

#389 Fixed User ID and Group ID attribute default value
  src/store/modules/SecurityAndAccess/LdapStore.js
Labels: vue3, 1060-vue3, 1110-vue3

#390 Fixed User ID and Group ID attribute default value
  src/store/modules/SecurityAndAccess/LdapStore.js
Labels: 1110, 1060

#391 Added Modal in Change password
  src/store/modules/SecurityAndAccess/UserManagementStore.js
  src/views/ChangePassword/ChangePassword.vue
  src/views/ProfileSettings/ProfileSettings.vue
Labels: 1110

#392 Updated network page toggle buttons
  src/store/modules/Settings/NetworkStore.js
  src/views/Settings/Network/NetworkInterfaceSettings.vue
Labels: 1110

#394 Update AFC upload popup message
  src/locales/en-US.json
Labels: 1110, 1060

#395 Updated network page toggle buttons - 1050, 1060
  src/store/modules/Settings/NetworkStore.js
  src/views/Settings/Network/NetworkInterfaceSettings.vue
Labels: 1050, 1060

#396 Updated Max value in TCE Table Pre-Allocation for Dynamic Drawer
  src/store/modules/ResourceManagement/ResourceMemoryStore.js
Labels: 1110

#397 Updated auto hide delay for success toast
  src/components/Composables/useToastComposable.js
  src/components/Global/Toast.vue
Labels: vue3, 1060-vue3, 1110-vue3

#393 Added DHCP NTP Servers list
  src/locales/en-US.json
  src/store/modules/Settings/DateTimeStore.js
  src/views/Settings/DateTime/DateTime.vue
Labels: 1110
