Repository ibm-openbmc/webui-vue, pull requests merged in 2025-01, with the labels that each got.

#330 Vue3:Memory page warning alert fix
  src/locales/en-US.json
Labels: vue3, 1110-vue3

#329 Memory page warning alert fix
  src/locales/en-US.json
Labels: 1110

#301 Prefix length fix
  src/store/modules/Settings/NetworkStore.js
  src/views/Settings/Network/ModalIpv6StaticDefaultGateway.vue
  src/views/Settings/Network/Network.vue
  src/views/Settings/Network/TableIpv6StaticDefaultGateway.vue
Labels: 1110

#334 Remove browser reload message
  src/locales/en-US.json
  src/store/modules/SecurityAndAccess/CertificatesStore.js
Labels: vue3, 1060-vue3, 1110-vue3

#335 Fix Content-Type in request header
  src/store/modules/SecurityAndAccess/CertificatesStore.js
Labels: vue3, 1060-vue3, 1110-vue3

#339 Fixed LEDs in Inventory and LEDs Page
  src/assets/styles/bmc/custom/_forms.scss
  src/store/modules/HardwareStatus/SystemStore.js
Labels: vue3, 1060-vue3, 1110-vue3

#336 Vue3: Add error toast message when CSR generation fails
  src/locales/en-US.json
  src/store/modules/SecurityAndAccess/CertificatesStore.js
  src/views/SecurityAndAccess/Certificates/ModalGenerateCsr.vue
Labels: vue3, 1060-vue3, 1110-vue3

#341 Fixed Delete in Deconfig Records
  src/locales/en-US.json
  src/views/Logs/DeconfigurationRecords/DeconfigurationRecords.vue
Labels: 1110

#324 Update User management page for MFA
  package-lock.json
  package.json
  src/components/Global/InfoTooltip.vue
  src/locales/en-US.json
  src/views/Login/Login.vue
  src/views/Login/ModalOtpGenerate.vue
  src/views/SecurityAndAccess/UserManagement/RegisterOtpModal.vue
  src/views/SecurityAndAccess/UserManagement/UserManagement.vue
  src/views/Settings/DateTime/DateTime.vue
Labels: 1110

#342 Updated the filter in Dumps: 1050, 1060
  src/views/Logs/Dumps/Dumps.vue
Labels: 1050, 1060

#332 Updated the filter in Dumps
  src/store/modules/Logs/DumpsStore.js
  src/views/Logs/Dumps/Dumps.vue
Labels: 1110

#350 Fixed empty alert in deconfig records
  src/views/Logs/DeconfigurationRecords/DeconfigurationRecords.vue
Labels: 1110

#343 Fixed frequency cap toggle issue for readonly users
  src/store/modules/ResourceManagement/SystemParametersStore.js
Labels: 1050, 1110, 1060

#352 Fixed Enabled power saver in Overview page: 1050,1060
  src/views/Overview/OverviewPower.vue
Labels: 1050, 1060

#351 Updated Overview power values
  src/views/Overview/OverviewPower.vue
Labels: 1110

#354 Implemented LLDP toggle uri change
  src/store/modules/Settings/NetworkStore.js
Labels: 1110

#358 Overview page OEM/Custom mode fix
  src/locales/en-US.json
  src/views/Overview/OverviewPower.vue
Labels: 1110

#359 1050: Fixed Resource dump and updated Message Ids
  src/utilities/GlobalConstants.js
  src/views/Logs/Dumps/DumpsForm.vue
  src/views/Operations/Firmware/FirmwareFormUpdate.vue
Labels: 1050

#361 Moved LLDP in Network page
  src/views/Settings/Network/Network.vue
  src/views/Settings/Network/NetworkInterfaceSettings.vue
Labels: 1110

#362 Fixed Delete All Event logs
  src/views/Logs/EventLogs/EventLogs.vue
Labels: 1110

#360 Updated maximum FCO value check
  src/views/ResourceManagement/FieldCoreOverride/FieldCoreOverrideConfiguration.vue
Labels: 1050, 1110, 1060

#364 Clear previous user's storedCurrentUser data
  src/store/modules/GlobalStore.js
Labels: 1050, 1110, 1060
