Repository ibm-openbmc/webui-vue, pull requests merged in 2025-08, with the labels that each got.

#444 Fixed dumps page modal and toast issue
  src/store/modules/Logs/DumpsStore.js
  src/views/Logs/Dumps/DumpsForm.vue
  src/views/Logs/Dumps/DumpsModalConfirmation.vue
  src/views/Logs/Dumps/DumpsPartitionModalConfirmation.vue
Labels: vue3, 1060-vue3

#438 Implemented Vitepress
  docs/.vitepress/components/colors/all.vue
  docs/.vitepress/components/colors/blues.vue
  docs/.vitepress/components/colors/colors.scss
  docs/.vitepress/components/colors/grays.vue
  docs/.vitepress/components/colors/greens.vue
  docs/.vitepress/components/colors/reds.vue
  docs/.vitepress/components/colors/theme.vue
  docs/.vitepress/components/colors/yellows.vue
  docs/.vitepress/config.js
  docs/.vitepress/styles/palette.styl
  docs/.vuepress/config.js
  docs/customization/index.md
  docs/customization/theme.md
  docs/guide/coding-standards/index.md
  docs/guide/components/alerts/index.md
  docs/guide/components/buttons/index.md
  docs/guide/components/file-upload/index.md
  docs/guide/components/index.md
  docs/guide/components/info-tooltip/index.md
  docs/guide/components/page-section/index.md
  docs/guide/components/page-title/index.md
  docs/guide/components/status-icon/index.md
  docs/guide/components/table/index.md
  docs/guide/components/toasts/index.md
  docs/guide/guidelines/colors.md
  docs/guide/guidelines/internationalization.md
  docs/guide/guidelines/motion.md
  docs/guide/index.md
  docs/guide/quickstart/forms.md
  docs/guide/quickstart/page-anatomy.md
  docs/guide/quickstart/store-anatomy.md
  docs/guide/unit-testing/index.md
  docs/index.md
  docs/public/openbmc-logo.svg
  docs/readme.md
  package-lock.json
  package.json
Labels: vue3, 1060-vue3

#441 Updated error toast message - 1050
  src/store/modules/Operations/ControlStore.js
  src/store/modules/Operations/FirmwareStore.js
  src/views/Operations/Firmware/FirmwareCardsBmc.vue
  src/views/Operations/Firmware/FirmwareFormUpdate.vue
  src/views/Operations/ServerPowerOperations/ServerPowerOperations.vue
Labels: 1050

#440 Updated error toast message
  src/store/modules/Operations/ControlStore.js
  src/store/modules/Operations/FirmwareStore.js
  src/views/Operations/Firmware/FirmwareCardsBmc.vue
  src/views/Operations/Firmware/FirmwareFormUpdate.vue
  src/views/Operations/ServerPowerOperations/ServerPowerOperations.vue
Labels: 1060

#429 Convert Hexa to ASCII in progress logs
  src/store/modules/Logs/PostCodeLogsStore.js
Labels: 1120, 1120-vue3-needed

#453 Fixed Asset tag in Vue3
  src/store/modules/HardwareStatus/SystemStore.js
  src/views/Overview/ModalAssetTag.vue
  src/views/Overview/OverviewServer.vue
Labels: vue3, 1060-vue3

#452 PCIe topology routing fix
  src/views/HardwareStatus/Inventory/InventoryTablePcieSlots.vue
  src/views/HardwareStatus/PcieTopology/PcieTopology.vue
Labels: vue3, 1060-vue3
