Repository ibm-openbmc/webui-vue, pull requests merged in 2025-09, with the labels that each got.

#457 Implemented Page not found
  src/env/router/ibm.js
  src/env/router/intel.js
  src/router/routes.js
  src/views/PageNotFound/PageNotFound.vue
Labels: vue3, 1060-vue3

#456 Fixed filter modal closing
  src/components/Global/TableFilter.vue
Labels: vue3, 1060-vue3

#459 New validation for ACF certificates
  src/locales/en-US.json
  src/store/modules/SecurityAndAccess/CertificatesStore.js
  src/views/Login/ModalUploadCertificate.vue
  src/views/SecurityAndAccess/Certificates/ModalGenerateCsr.vue
  src/views/SecurityAndAccess/Certificates/ModalUploadCertificate.vue
Labels: 1120, 1110.10, 1120-vue3-needed, 1110-vue3-needed

#460 Vue3 Styling fixes
  src/assets/styles/bmc/custom/_tables.scss
  src/components/AppHeader/AppHeader.vue
  src/components/AppNavigation/AppNavigation.vue
  src/views/HardwareStatus/ConcurrentMaintenance/ConcurrentMaintenance.vue
  src/views/HardwareStatus/Inventory/Inventory.vue
  src/views/HardwareStatus/Inventory/InventoryFabricAdapters.vue
  src/views/HardwareStatus/Inventory/InventoryTableBmcManager.vue
  src/views/HardwareStatus/Inventory/InventoryTableDimmSlot.vue
  src/views/HardwareStatus/Inventory/InventoryTableFans.vue
  src/views/HardwareStatus/Inventory/InventoryTablePcieSlots.vue
  src/views/HardwareStatus/Inventory/InventoryTablePowerSupplies.vue
  src/views/HardwareStatus/Inventory/InventoryTableProcessors.vue
  src/views/HardwareStatus/Inventory/InventoryTableSystem.vue
  src/views/HardwareStatus/PcieTopology/PcieTopology.vue
  src/views/Logs/AuditLogs/AuditLogs.vue
  src/views/Logs/DeconfigurationRecords/DeconfigurationRecords.vue
  src/views/Logs/Dumps/Dumps.vue
  src/views/Logs/EventLogs/EventLogs.vue
  src/views/Logs/PostCodeLogs/PostCodeLogs.vue
  src/views/Operations/Firmware/Firmware.vue
  src/views/Operations/HostConsole/HostConsoleConsole.vue
  src/views/Operations/Kvm/KvmConsole.vue
  src/views/Operations/ServerPowerOperations/ServerPowerOperations.vue
  src/views/Operations/ServiceLoginConsoles/ServiceLoginConsoles.vue
  src/views/Overview/OverviewCard.vue
  src/views/ResourceManagement/CapacityOnDemand/CapacityOnDemandOrderInfo.vue
  src/views/ResourceManagement/Memory/Memory.vue
  src/views/SecurityAndAccess/Ldap/Ldap.vue
  src/views/SecurityAndAccess/Sessions/Sessions.vue
  src/views/Settings/DateTime/DateTime.vue
  src/views/Settings/HardwareDeconfiguration/HardwareDeconfiguration.vue
Labels: vue3, 1060-vue3

#446 Fixed Vite config and env based config
  .env.ibm
  .env.intel
  .eslintrc.cjs
  package-lock.json
  package.json
  src/env/components/AppNavigation/ibm.js
  src/store/api.js
  vite.config.js
Labels: vue3, 1060-vue3

#467 Fixed service validation
  src/views/Login/ModalUploadCertificate.vue
Labels: 1120, 1110.10

#473 Fixed consoles in new tab and progress codes
  package-lock.json
  package.json
  src/env/router/ibm.js
  src/views/Logs/PostCodeLogs/PostCodes.vue
Labels: vue3, 1060-vue3

#472 Fixed read-only submit
  src/views/SecurityAndAccess/UserManagement/ModalUser.vue
Labels: vue3, 1060-vue3

#479 Fixed BMC and server reset
  src/store/modules/Operations/FactoryResetStore.js
Labels: 1120, 1120-vue3-needed

#480 Documentation Updates
  docs/.vitepress/components/colors/reds.vue
  docs/.vitepress/components/colors/theme.vue
  docs/.vitepress/components/colors/yellows.vue
  docs/.vitepress/theme/index.js
  docs/customization/index.md
  docs/customization/theme.md
  docs/guide/coding-standards/accessibility.md
  docs/guide/components/file-upload/index.md
  docs/guide/components/info-tooltip/index.md
  docs/guide/components/table/index.md
  docs/guide/guidelines/colors.md
  docs/guide/guidelines/internationalization.md
  docs/guide/index.md
  docs/guide/quickstart/page-anatomy.md
Labels: vue3, 1060-vue3
