Repository ibm-openbmc/webui-vue, pull requests merged in 2025-02, with the labels that each got.

#348 Implemented Capacity on Demand page
  src/router/routes.js
  src/views/ResourceManagement/CapacityOnDemand/CapacityOnDemand.vue
  src/views/ResourceManagement/CapacityOnDemand/CapacityOnDemandActivation.vue
  src/views/ResourceManagement/CapacityOnDemand/CapacityOnDemandOrderInfo.vue
  src/views/ResourceManagement/CapacityOnDemand/CapacityOnDemandTable.vue
Labels: vue3, 1060-vue3, 1110-vue3

#366 Implement Host console page
  package-lock.json
  package.json
  src/assets/styles/bmc/custom/_sol.scss
  src/router/routes.js
  src/store/modules/HardwareStatus/ChassisStore.js
  src/views/Operations/HostConsole/HostConsole.vue
  src/views/Operations/HostConsole/HostConsoleConsole.vue
Labels: vue3, 1060-vue3, 1110-vue3

#328 Implemented Deconfiguration Records page - 1060
  src/components/Composables/useTableSelectableComposable.js
  src/router/routes.js
  src/store/index.js
  src/store/modules/Logs/DeconfigurationRecordsStore.js
  src/views/Logs/DeconfigurationRecords/DeconfigurationRecords.vue
Labels: vue3, 1060-vue3

#338 Implemented Deconfiguration records page - 1110
  src/components/Composables/useTableSelectableComposable.js
  src/locales/en-US.json
  src/router/routes.js
  src/store/index.js
  src/store/modules/Logs/DeconfigurationRecordsStore.js
  src/views/Logs/DeconfigurationRecords/DeconfigurationRecords.vue
Labels: vue3, 1110-vue3

#344 Implemented Server power operations page
  package-lock.json
  package.json
  src/assets/styles/bmc/custom/_tables.scss
  src/components/AppHeader/AppHeader.vue
  src/layouts/AppLayout.vue
  src/locales/en-US.json
  src/main.js
  src/router/routes.js
  src/store/index.js
  src/store/modules/Authentication/AuthenticationStore.js
  src/store/modules/GlobalStore.js
  src/store/modules/Operations/BootSettingsStore.js
  src/store/modules/Operations/ControlStore.js
  src/store/modules/Operations/NetworkSettingsStore.js
  src/store/modules/Settings/NetworkStore.js
  src/store/plugins/WebSocketPlugin.js
  src/views/Operations/ServerPowerOperations/BiosSettings.vue
  src/views/Operations/ServerPowerOperations/BootSettings.vue
  src/views/Operations/ServerPowerOperations/NetworkSettingsModal.vue
  src/views/Operations/ServerPowerOperations/ServerPowerOperations.vue
  src/views/Overview/OverviewNetwork.vue
  vite.config.js
Labels: vue3, 1060-vue3

#368 Implemented LDAP Page
  src/components/Composables/useTableSelectableComposable.js
  src/components/Global/InputPasswordToggle.vue
  src/router/routes.js
  src/store/index.js
  src/store/modules/SecurityAndAccess/LdapStore.js
  src/store/modules/SecurityAndAccess/UserManagementStore.js
  src/views/SecurityAndAccess/Ldap/Ldap.vue
  src/views/SecurityAndAccess/Ldap/ModalAddRoleGroup.vue
  src/views/SecurityAndAccess/Ldap/TableRoleGroups.vue
Labels: vue3, 1060-vue3, 1110-vue3

#367 Implemented Event logs
  src/components/Composables/useTableSelectableComposable.js
  src/router/routes.js
  src/store/modules/Logs/EventLogStore.js
  src/views/Logs/EventLogs/EventLogs.vue
Labels: vue3, 1060-vue3, 1110-vue3

#369 Added Memory Alert in Hardware Deconfiguration Page
  src/locales/en-US.json
  src/views/Settings/HardwareDeconfiguration/HardwareDeconfiguration.vue
Labels: 1050, 1110, 1060

#357 Removed MFA for LDAP and fixed error message
  src/store/modules/GlobalStore.js
  src/store/modules/SecurityAndAccess/UserManagementStore.js
  src/views/SecurityAndAccess/UserManagement/ModalUser.vue
  src/views/SecurityAndAccess/UserManagement/UserManagement.vue
Labels: 1110

#370 1110: Fixed IO slots in PCIe topology
  src/store/modules/HardwareStatus/PcieTopologyStore.js
  src/views/HardwareStatus/PcieTopology/IdentifyLedsModal.vue
Labels: 1110

#371 1060: Fixed IO slots in PCIe topology
  src/store/modules/HardwareStatus/PcieTopologyStore.js
  src/views/HardwareStatus/PcieTopology/IdentifyLedsModal.vue
Labels: 1060

#372 1050: Fixed IO slots in PCIe topology
  src/store/modules/HardwareStatus/PcieTopologyStore.js
  src/views/HardwareStatus/PcieTopology/IdentifyLedsModal.vue
Labels: 1050

#374 Add table refresh when request fails
  src/store/api.js
  src/store/modules/HardwareStatus/AssemblyStore.js
  src/store/modules/HardwareStatus/FabricAdaptersStore.js
  src/store/modules/HardwareStatus/FanStore.js
  src/store/modules/HardwareStatus/PowerSupplyStore.js
  src/views/HardwareStatus/Inventory/InventoryFabricAdapters.vue
Labels: 1050, 1110, 1060

#375 Revert commit 334
  src/locales/en-US.json
  src/store/modules/SecurityAndAccess/CertificatesStore.js
Labels: vue3, 1060-vue3, 1110-vue3

#378 Updated Chassis version
  src/store/modules/HardwareStatus/ChassisStore.js
Labels: 1110

#379 Update Safe mode
  src/store/modules/GlobalStore.js
Labels: 1110
