Repository ibm-openbmc/webui-vue, pull requests merged in 2025-05, with the labels that each got.

#408 Updated notices page - 1110
  src/views/Notices/NoticesText.vue
Labels: 1110

#409 Fixed System setting issue in Inventory and LEDs
  src/store/modules/HardwareStatus/SystemStore.js
Labels: 1050, 1110, 1060

#410 Fixed error message for BMC dump
  src/store/modules/Logs/DumpsStore.js
Labels: 1110

#411 Fixed error message for BMC dump: 1050, 1060
  src/store/modules/Logs/DumpsStore.js
Labels: 1050, 1060

#406 Implemented Dumps page - 1060
  src/components/Global/TableRowAction.vue
  src/locales/en-US.json
  src/router/routes.js
  src/store/index.js
  src/store/modules/Logs/DumpsStore.js
  src/views/Logs/Dumps/Dumps.vue
  src/views/Logs/Dumps/DumpsForm.vue
  src/views/Logs/Dumps/DumpsModalConfirmation.vue
  src/views/Logs/Dumps/DumpsPartitionModalConfirmation.vue
Labels: vue3, 1060-vue3

#407 Implemented Date and Time in Vue3
  src/store/modules/Settings/DateTimeStore.js
  src/views/Settings/DateTime/DateTime.vue
Labels: vue3, 1060-vue3, 1110-vue3

#399 Implemented dumps page
  src/components/Global/TableRowAction.vue
  src/locales/en-US.json
  src/router/routes.js
  src/store/index.js
  src/store/modules/Logs/DumpsStore.js
  src/views/Logs/Dumps/Dumps.vue
  src/views/Logs/Dumps/DumpsForm.vue
  src/views/Logs/Dumps/DumpsModalConfirmation.vue
  src/views/Logs/Dumps/DumpsPartitionModalConfirmation.vue
Labels: vue3, 1110-vue3

#412 Updated Notices text page
  src/views/Notices/NoticesText.vue
Labels: vue3, 1110-vue3

#417 Updated data-test-id for Secret key
  src/views/SecurityAndAccess/UserManagement/UserManagement.vue
Labels: 1110

#416 Updated Overview page - power mode section
  src/views/Overview/OverviewPower.vue
Labels: vue3, 1060-vue3

#418 Fixed Styling issues in Table filter
  src/assets/styles/bmc/custom/_forms.scss
  src/components/Global/TableFilter.vue
  src/views/ResourceManagement/FieldCoreOverride/FieldCoreOverrideConfiguration.vue
Labels: vue3, 1060-vue3, 1110-vue3

#419 Added data-test-id for TOTP
  src/views/Login/Login.vue
Labels: 1110
